version: '2.1'


services:

  rtmpserver:
    build: ./images/rtmpserver
    ports:
      - 1935:1935
      - 1936:1936
    restart: always
    volumes:
      - $PWD/tmp:/tmp
    networks:
      webcam-network:
        ipv4_address: 172.22.2.2
        aliases:
          - rtmpserver

  ffmpeg:
    #image: ffmpeg
    build: ./images/ffmpeg
    links:
      - "rtmpserver"
    depends_on:
      - "rtmpserver"
    #command: "ffmpeg -f mjpeg -i "http://webcam:fsmpi@olaf.fs.uni-bayreuth.de/video.cgi" -f flv rtmp://rtmpserver/live"
    restart: always
    networks:
      webcam-network:
        ipv4_address: 172.22.2.3
        aliases:
          - ffmpeg


networks:
  webcam-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.2.0/24
